OpenlyOne/openly

.travis.yml
spec/rails_helper.rb

Only start/run SimpleCov when environment variable 'CI' or 'COVERAGE' is set to true. For Travis, we set 'CI' to true.

Limit SimpleCov Use

---

app/views/application/_navbar.slim
app/views/layouts/application.slim
app/views/static/index.slim

According to Slim Templating docs, use '=' for output that you want to
be HTML escaped and use '==' for output that you do not want to have
HTML escaped. Using '=' we are on the safer side (making unescaped HTML
the exception rather than the default).

Modify templates to use '=' instead of '=='

---

app/views/layouts/application.slim

We will first build a non-JS based website without Turbolinks and MaterialJS.
This ensures that our site is fully non-JS compatible. It also focuses our
resources on development rather than maintaining compatibility.

Disable JavaScript

---

app/assets/stylesheets/shared.scss
app/views/static/index.slim

Vertical spacing class should follow the format v..px to symbolize 'vertical' (rather than h..px). The use of h..px was an accident.

Fix: Rename vertical spacing class

---

.scss-lint.yml

Do not recommend leading zeros for non-integer values. This is the default but we are making it explicit since Hound does not have it as its default value.

SCSS-Lint: Exclude leading zeros

---

app/models/user.rb
spec/models/user_spec.rb

Mark account_id as readonly on User model to prevent changes in the account-user relationship.

Account-user relationship cannot be altered

---

app/controllers/application_controller.rb
config/locales/devise.en.yml
config/routes.rb
spec/features/session_spec.rb
spec/routing/session_routing_spec.rb

When user visits page for which authentication is required, redirect them to the login page. Upon successful login, redirect user back to the page they originally requested.

Devise: Prompt login when unauthenticated

---

Guardfile

Run view spec when template is updated. The file name for view spec should not include the file ending. It should just be 'show_spec.rb' rather than 'show.html.erb_spec.rb' or 'show.slim_spec.rb'.

Fix: Guardfile configuration for view specs

---

app/assets/stylesheets/shared/forms.scss

Style placeholders to resemble parent input element in terms of color and size.

Fix: Styling for form input placeholders

---

app/models/project.rb
spec/models/project_spec.rb

Extend Project.find method to restore its use of finding records by ID. This allows us to use methods, such as #reload, that depend on the original behavior of .find.

Projects can be found by ID

---

config/deploy.rb
config/settings/production.yml
db/migrate/20170813131934_disable_null_on_project_owner.rb
db/schema.rb
db/seeds.rb

- Prevent null values for project owners
- Clear file storage before seeding database
- Use system/ directory for file storage in production
- Capistrano: Add file storage directory to linked directories

Fix: Version Control

---

app/models/version_control/file.rb
app/models/version_control/file_collection.rb
spec/models/version_control/file_collection_spec.rb

- Fix: Explicitly create VersionControl::File
- Fix: FileCollection ignores case when finding files
- Fix: Allow empty arguments for VersionControl::File.new
- Add method: VersionControl::FileCollection#exists?

Fix Version Control

---

app/models/concerns/version_control.rb
app/models/version_control/file.rb
app/models/version_control/file_collection.rb
spec/factories/version_control/file.rb
spec/models/shared_examples/having_dirty_tracked_attribute.rb
spec/models/version_control/file_collection_spec.rb
spec/models/version_control/file_spec.rb
spec/models/version_control/repository_spec.rb

Implement ActiveRecord-like methods to make VersionControl::File behave as if it
was a tableless ActiveRecord object. The implemented behaviors are:
- Validations
- Dirty tracking (tracking changes)
- Persistence checking
- Creating a record
- Updating a record
- Destroying a record

Modelize VersionControl::File

---

app/models/version_control/file.rb
spec/models/version_control/file_spec.rb

When calling VersionControl::File#content on instances where @content is
nil and @oid is nil, an error would occur. This was due to the fact that
Rugged::Repository#lookup raises an error if a non-string parameter is
passed. This fixes the problem by only calling lookup if
VersionControl::File#oid is not nil.

Fix: VersionControl::File#content is nil for new instances

---

app/assets/stylesheets/shared/forms.scss

Input elements that inherit styling from its parent container (for
example, input elements that imitate the look of a heading) do not
override border color when they have class 'invalid'. This allows them
to match other invalid input elements which are also red underlined.

Fix: Enable invalid styling on inherited input

---

spec/factories/version_control/file.rb

The paragraphs generated by Faker must be joined by "\n\n" rather than '\n\n'. The line break character \n is escaped if it is written with single quotes.

Fix vc_file factory: Line breaks in content

---

app/assets/stylesheets/shared/all.scss
app/assets/stylesheets/shared/border.scss
app/views/devise/registrations/_card.slim

We added a border top to all card titles when we created cards for each of a user's projects (on the users#show page). However, the card on the registration page is not meant to have a top border.

Join Upshift page: Remove border top from card

---

app/views/application/_navbar.slim

When the HTML page is loaded and rendered before the stylesheet is loaded, the logo is sometimes rendered at full page size. Add explicit width and height (42px * 42px) into the HTML tag to avoid this problem.

Fix: Navbar: Set logo size in HTML tag

---

app/assets/stylesheets/shared/buttons.scss

Remove the spacing between the banner and the heading ('Overview').

Fix: Projects#show: Remove margin between banner and text

---

app/assets/stylesheets/shared/chips.scss

Truncate chips at max-width of 100%.

Fix: Prevent chips from overflowing

---

app/models/discussions/base.rb
app/models/user.rb
spec/factories/replies.rb
spec/features/account_spec.rb
spec/models/shared_examples/being_a_discussion.rb
spec/models/user_spec.rb

When destroying user, ...
- destroy initiated discussions
- destroy authored replies
When destroying discussion, ...
- destroy associated replies

Fix: Avoid foreign key constraint error

---

CHANGELOG.md
app/models/google_drive.rb
config/application.yml.example

- Fix: Support absolute path for Google credentials file
On our production environment, we need to refer to the credentials file not from our user's home directory but from an absolute path. This commit switches support from relative to absolute paths.

Hotfix 0.6.1

---

db/migrate/20180108180921_drop_notification_channels.rb
db/schema.rb

The table has never been used (we never had a model NotificationChannel). It was added in c872e6aad39671869ca8c9fd11ba8f50ae8994e3. It probably sneaked in when switching back and forth between different Git branches.

Fix: Drop DB table 'notification_channels'

---

Capfile
Gemfile
Gemfile.lock
app/jobs/error_report_job.rb
app/models/account.rb
config/application.yml.example
config/deploy.rb
config/initializers/rollbar.rb
spec/jobs/error_report_job_spec.rb
spec/lib/error_reporting_spec.rb
spec/models/account_spec.rb

Add gem 'rollbar' to report production-level errors to Rollbar. Errors from
both the web application and from background jobs are reported.

Track production errors with Rollbar

---

app/assets/stylesheets/shared/forms.scss

Grammarly adds a div each before and after every textarea. This caused
the textarea label to not correctly position itself above the textarea
and resulted in an overlap between label and input area.

Fix: Textarea display for Grammarly users

---

app/models/account.rb
app/views/devise/sessions/new.slim
config/initializers/devise.rb
db/migrate/20180120045232_add_remember_created_at_to_accounts.rb
db/schema.rb
spec/features/session_spec.rb
spec/models/account_spec.rb

When a user logs in and checks 'Remember me', the logged in account is
remembered for up to one week. If the user revisits that site during
the week, the period is extended for another week, etc...

Devise: Remember logged-in accounts for one week

---

app/controllers/profiles_controller.rb
app/views/profiles/edit.slim
app/views/profiles/show.slim
db/migrate/20180128202117_add_about_to_profiles.rb
db/schema.rb
spec/controllers/profiles_controller_spec.rb
spec/factories/profiles/base.rb
spec/features/user_spec.rb
spec/views/profiles/edit_spec.rb
spec/views/profiles/show_spec.rb

Profiles have an about field that is displayed on their profile page and can be used by the profile owner to provide additional information about the profile.

Add 'About' to Profiles

---

app/controllers/projects_controller.rb
app/views/profiles/show.slim
app/views/projects/_form.slim
app/views/projects/_project.slim
app/views/projects/show.slim
db/migrate/20180128205442_add_description_to_projects.rb
db/schema.rb
spec/factories/projects.rb
spec/features/project_spec.rb
spec/views/profiles/show_spec.rb
spec/views/projects/edit_spec.rb
spec/views/projects/show_spec.rb

Projects have a description field that is displayed on the project#show page and can be used by the project owner to provide additional information about the project.

Add 'Description' to Projects

---

app/assets/stylesheets/shared/all.scss
app/assets/stylesheets/shared/cards.scss
app/assets/stylesheets/shared/general.scss
app/controllers/projects_controller.rb
app/helpers/tag_helper.rb
app/models/project.rb
app/views/projects/_form.slim
app/views/projects/_project.slim
app/views/projects/show.slim
db/migrate/20180128221502_add_tags_to_projects.rb
db/schema.rb
spec/factories/projects.rb
spec/features/project_spec.rb
spec/helpers/tag_helper_spec.rb
spec/models/project_spec.rb
spec/views/profiles/show_spec.rb
spec/views/projects/edit_spec.rb
spec/views/projects/show_spec.rb

Projects have tags that are displayed on the project#show page. The project
owner can be supply project tags to highlight particular keywords associated
with the project.

Add Tags to Projects

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb

Install and configure gem 'capistrano3-delayed-job' for Capistrano-DelayedJob integration.

Automatically restart DelayedJob on deployment

---

.rubocop.yml
db/migrate/20171120015812_create_file_items.rb
db/migrate/20171122062359_drop_discussions_and_replies.rb
db/migrate/20171122221645_create_delayed_jobs.rb
db/migrate/20180108071756_drop_table_file_items.rb

Migrations can be quite long, depending on the number of columns of the
database table. There is no point in limiting MethodLength for
migrations.

Rubocop: Ignore MethodLength and AbcSize in migrations

---

app/models/concerns/snapshotable.rb
app/models/file_resource/snapshot.rb
spec/integrations/file_resources/google_drive_spec.rb
spec/integrations/shared_examples/including_snapshotable_integration.rb
spec/integrations/shared_examples/including_stageable_integration.rb
spec/models/file_resource/snapshot_spec.rb
spec/models/shared_examples/being_a_file_resource.rb

When setting a current snapshot for a snapshotable object, the current snapshot must belong to the snapshotable object.

Validate: Current snapshot must belong to snapshotable

---

Gemfile
app/models/committed_file.rb
app/models/file_diff.rb
app/models/revision.rb
app/models/revision/file_ancestry_tree.rb
app/models/revision/file_diffs_calculator.rb
db/migrate/20180227150638_create_file_diffs.rb
db/schema.rb
lib/tasks/performance/generate_diffs_for_origin_revision.rake
lib/tasks/performance/generate_diffs_for_origin_revision/cleanup.rake
lib/tasks/performance/generate_diffs_for_origin_revision/prepare.rake
lib/tasks/performance/generate_diffs_for_origin_revision/test.rake
lib/tasks/performance/generate_diffs_for_revision_with_parent.rake
lib/tasks/performance/generate_diffs_for_revision_with_parent/cleanup.rake
lib/tasks/performance/generate_diffs_for_revision_with_parent/prepare.rake
lib/tasks/performance/generate_diffs_for_revision_with_parent/test.rake
spec/factories/file_diffs.rb
spec/integrations/revision/file_diffs_calculator_spec.rb
spec/models/committed_file_spec.rb
spec/models/file_diff_spec.rb
spec/models/revision/file_ancestry_tree_spec.rb
spec/models/revision/file_diffs_calculator_spec.rb
spec/models/revision_spec.rb

- Add FileDiff model for storing cached file diffs between revisions
- Add Revision::FileDiffCalculator for calculating and persisting diffs to cache
- Add Revision::FileAncestryTree for calculating ancestor names for diffs

Implement DB-backed File Diffs

---

.travis.yml

Integration spec for Revision::FileDiffCalculator is working locally but failing on Travis. This is probably due to the PostgreSQL being v9.2 and the json_agg() function being unsupported in versions v9.2 and earlier.

Travis: Use PSQL 9.6

---

spec/integrations/project_spec.rb

Do not expect specific ordering of records returned by Project#non_root_file_resources_in_stage.with_current_snapshot

Fix: Project integration spec

---

app/models/project.rb
app/models/revision.rb
spec/models/project_spec.rb
spec/models/revision_spec.rb

- Project#revisions refers to published revisions
- On destroy, Project first deletes the staged root folder (because staged
files are readonly, delete must be used rather than destroy and the staged
root folder must be deleted prior to destroying the remainder of staged
files)

Fix: Project

---

app/models/revision/file_ancestry_tree.rb
spec/integrations/revision/file_ancestry_tree_spec.rb
spec/models/revision/file_ancestry_tree_spec.rb

When generating ancestry tree, load generations depth+1 times because
the first generation is just that of the children. So if we want an
ancestry tree with depth 3, we have to load generations 4 times.

Fix: FileAncestryTree.generate

---

app/models/concerns/diffing.rb
app/models/file_diff.rb
app/models/project.rb
app/models/revision.rb
app/models/stage/file_diff.rb
app/models/stage/file_diff/ancestry.rb
app/models/stage/file_diff/children.rb
spec/factories/stage/file_diffs.rb
spec/integrations/stage/file_diff/ancestry_spec.rb
spec/integrations/stage/file_diff/children_spec.rb
spec/integrations/stage/file_diff_spec.rb
spec/models/file_diff_spec.rb
spec/models/project_spec.rb
spec/models/shared_examples/being_diffing.rb
spec/models/stage/file_diff/ancestry_spec.rb
spec/models/stage/file_diff/children_spec.rb
spec/models/stage/file_diff_spec.rb

Use Stage::FileDiff.find_by! to calculate diff for staged files and access
diffing methods (added?, changed?, ...) as well as children and ancestors.

Add Stage::FileDiff for diffing staged files

---

app/controllers/errors_controller.rb

Do not verify authenticity token when rendering an error page, such as
404, 422, or 500. This is necessary, so that a POST request that triggers an
error still correctly renders errors.

Error pages: Do not verify authenticity token

---

app/models/revision.rb
spec/integrations/project_spec.rb
spec/models/revision_spec.rb

Set correct setting for dependent key on has_many associations on
project and revisions. This is to make sure that all associations are
successfully deleted when project is deleted and we have no foreign key
violations or orphaned records.

Fix: Project#destroy not to raise error

---

app/controllers/concerns/can_set_project_context.rb
app/controllers/file_infos_controller.rb
app/controllers/folders_controller.rb
app/controllers/projects_controller.rb
app/controllers/revisions_controller.rb
app/models/ability.rb
app/models/project.rb
app/views/projects/new.slim
db/migrate/20180307044915_add_is_public_to_projects.rb
db/schema.rb
spec/controllers/file_infos_controller_spec.rb
spec/controllers/folders_controller_spec.rb
spec/controllers/projects_controller_spec.rb
spec/controllers/revisions_controller_spec.rb
spec/controllers/shared_examples/an_authorized_action.rb
spec/controllers/shared_examples/authorizing_project_access.rb
spec/factories/projects.rb
spec/features/collaborator_spec.rb
spec/features/file_info_spec.rb
spec/features/file_update_spec.rb
spec/features/folder_spec.rb
spec/features/project_spec.rb
spec/features/revision_spec.rb
spec/models/ability_spec.rb
spec/views/projects/new_spec.rb

Projects can be private (accessible only by owner and collaborators) or public (accessible by everyone). Projects are private by default.

Add support for private projects

---

app/models/revision.rb
app/views/file_infos/_new_file_changes.slim
app/views/folders/show.slim
app/views/revisions/new.slim
spec/features/collaborator_spec.rb
spec/features/revision_spec.rb
spec/views/file_infos/index_spec.rb
spec/views/folders/show_spec.rb
spec/views/revisions/new_spec.rb

Replace any occurrence of 'Commit Changes' with 'Capture Changes'. Commit
is a word specific to the programming community and is generally
confusing to others. We will see if the idea of capturing changes is a
bit more clear.

Use language: Capture Changes

---

app/models/ahoy/event.rb
app/models/ahoy/visit.rb
spec/models/ahoy/event_spec.rb
spec/models/ahoy/visit_spec.rb

Provide the class name (Profiles::User) for the user association on Ahoy
models Visit and Event, because the class name cannot be inferred from
the association name.

Fix Ahoy: Provide class name for user association

---

app/models/profiles/base.rb
app/models/project.rb
db/migrate/20180314010314_remove_owner_type_from_projects.rb
db/schema.rb
spec/models/project_spec.rb
spec/models/shared_examples/being_a_profile.rb

Make project's owner association non-polymorphic. The polymorphic
association was necessary when we had different models & tables for
users and teams, but since they both share the profiles table, we can
remove the polymorphic association.

Project: Remove polymorphism from owner association

---

config/deploy.rb
lib/tasks/accounts/create_from_csv.rake
spec/lib/shared_contexts/rake.rb
spec/lib/tasks/accounts_create_from_csv_spec.rb
spec/support/fixtures/accounts/import.csv

Add task for importing accounts from a csv file. Path to file must be passed as the argument to the task:
rake accounts:create_from_csv['path']
And the csv file must have the headers name, email, password, and handle.

Add accounts:create_from_csv task

---

app/controllers/concerns/can_set_project_context.rb
app/views/projects/access_unauthorized.slim
spec/views/projects/access_unauthorized_spec.rb

Show custom access-unauthorized error page when user tries to access a project for which they are unauthorized.

Add custom page for unauthorized access to project

---

app/controllers/application_controller.rb
spec/features/session_spec.rb

When a user logs in, redirect the user back to the page they last visited - unless that page is the home page.
The fallback redirect location is the user's profile page.

After login, redirect user back to previous page

---

app/assets/stylesheets/shared/forms.scss

Inputs with .inherit class now inherit their parent element's color style.

Fix: Input .inherit inherits color

---

spec/features/folder_spec.rb

Use SQL sorting to assert correct sort order in folders#show. This is
necessary because Ruby sorting results in a different sort order than
SQL does. See: https://stackoverflow.com/a/44271968/6451879

Fix: Folder spec

---

app/assets/stylesheets/shared/cards.scss
app/controllers/profiles_controller.rb
app/controllers/resources_controller.rb
app/models/profiles/base.rb
app/models/resource.rb
app/views/profiles/show.slim
app/views/resources/_resource.slim
config/routes.rb
db/migrate/20180414050240_create_resources.rb
db/schema.rb
spec/controllers/resources_controller_spec.rb
spec/factories/resources.rb
spec/models/notification_spec.rb
spec/models/resource_spec.rb
spec/models/shared_examples/acting_as_hash_id.rb
spec/models/shared_examples/being_a_profile.rb
spec/routing/resource_routing_spec.rb
spec/views/profiles/show_spec.rb

Profiles can own resources (such as Google Drive files). Resources are listed on a profile's page. Currently, resources must be added via CLI, not in-app.

Add resources to profiles

---

CHANGELOG.md
README.md
app/models/providers/google_drive/link.rb
spec/factories/file_resource/snapshots.rb
spec/models/providers/google_drive/link_spec.rb
spec/regressions/views/revisions/index_spec.rb

Fixed a bug where the Files and Revisions pages would break if they contained a PDF document.

Hotfix v0.22.1

---

app/views/layouts/application.slim

Use 'blue darken-2' as the app-wide color scheme. This overrides the
previous random rainbow color scheme. We are choosing a consistent
color scheme because it looks more professional.

App color scheme: Set to 'blue darken-2'

---

CHANGELOG.md
README.md
config/deploy.rb

**Fixes:**
- Bump Capistrano version in deploy.rb to v3.11.0 (to reenable Capistrano CLI)

Hotfix v0.26.1: Fix Capistrano deploy version

---

.gitignore

Ignore public spec directory to avoid tracking files generated during
RSpec tests.

Git: Ignore /public/spec

---

app/controllers/notifications_controller.rb
app/models/project.rb
app/views/notifications/_vcs_commit_notification.slim
spec/factories/notifications.rb
spec/features/notification_spec.rb
spec/mailers/notifications_mailer_spec.rb
spec/models/project_spec.rb
spec/views/notifications/index_spec.rb

Fix notifications to be compatible with VCS::Commit as notifiable. The
key issue is that VCS::Commit has no relationship to our top-level
model project. We do not yet have a strategy for how to handle the
relationship between the models in the VCS namespace and everything
outside.

Fix Notifications

---

CHANGELOG.md
app/models/vcs/branch.rb
spec/integrations/vcs/branch_spec.rb

This fix resolves the following issue:
1) A folder exists in branch A
2) The folder is moved to another branch B, but an instance of
VCS::StagedFile with its external id and current_snapshot_id = NULL
and committed_snapshot_id = NULL still exists in branch A
3) A file is added to the folder
4) FileUpdateJob wants to add file to branches A & B. It fails trying to
add it to branch A when validating that file its not its own
ancestor.
This issue is fixed by pulling file updates only to branches where the
parent is actually staged (i.e. current or committed snapshot is
present).

Hotfix v0.27.1: Pull FileUpdateJob updates only to branches w/ staged files

---

config/deploy.rb

When generating the 500 error page, curl is called on the hostname with
path 500. In our case, the hostname is openly.one but the error page
lives at www.openly.one. Curl did not follow the redirect, so the 500
page became a 'moved permanently' message. Add flag -L to instruct curl
to follow redirects.
[ci skip] because no testable files were touched.

Capistrano: Fix 500 page generation

---

.gitignore
.travis.yml
config/deploy.rb
config/settings.yml
config/settings/test.yml
lib/tasks/backup/all.rake
lib/tasks/backup/attachments.rake
lib/tasks/backup/attachments/attachments_backup_task_helper.rb
lib/tasks/backup/attachments/capture.rake
lib/tasks/backup/attachments/create_directory.rake
lib/tasks/backup/backup_task_helper.rb
lib/tasks/backup/database.rake
lib/tasks/backup/database/capture.rake
lib/tasks/backup/database/create_directory.rake
lib/tasks/backup/database/database_backup_task_helper.rb
spec/lib/shared_contexts/rake.rb
spec/lib/tasks/accounts_create_from_csv_spec.rb
spec/lib/tasks/backup/all_spec.rb
spec/lib/tasks/backup/attachments_spec.rb
spec/lib/tasks/backup/database_spec.rb
spec/lib/tasks/data_migration/file_snapshots_content_spec.rb
spec/lib/tasks/data_migration/file_thumbnails_spec.rb
spec/rails_helper.rb
spec/support/database_cleaner.rb

When code has been pushed to the server but prior to running migrations,
perform a database and attachments backup.
The database can also be backed up by manually running the backup:database rake
task in the desired Rails environment. Backups are created using `pg_dump` and
are stored in a backup directory.
The attachments can also be backed up by manually running the backup:attachments
rake task in the desired Rails environment. Backups are created using recursive copy
and are stored in a backup directory.

Backup database & attachments on deploy

---

app/models/vcs/commit.rb
app/models/vcs/operations/content_differ.rb
app/models/vcs/version.rb

Remove dead code artifacts that have remained in VCS library from a long
time ago when we were migrating from the single-source to the
multi-source model. This will slightly increase code coverage.

Remove code that is unused

---

CHANGELOG.md
db/migrate/20181204165449_rename_file_thumbnails_to_thumbnails.rb

We accidentally modified the migration while doing a find-and-replace
for `file_thumbnails`. This fixes that by reverting the original table
name back to `file_thumbnails`.

Hotfix v0.30.1: Fix RenameFileThumbnailsToThumbnailsMigration

---

CHANGELOG.md
app/models/concerns/vcs/syncable.rb
app/views/folders/_ancestor.slim
spec/factories/vcs/vcs_file_in_branches.rb
spec/regressions/integrations/vcs/file_in_branch_spec.rb
spec/support/fixtures/vcr_cassettes/VCS_FileInBranch/_pull_children/does_NOT_updates_subfile1_and_subfile2_name.yml
spec/support/fixtures/vcr_cassettes/VCS_FileInBranch/_pull_children/updates_subfile1_and_subfile2_parent.yml
spec/support/fixtures/vcr_cassettes/VCS_FileInBranch/_pull_children/when_some_children_are_new/creates_and_pulls_subfile1_and_subfile2.yml
spec/support/fixtures/vcr_cassettes/VCS_FileInBranch/_pull_children/when_some_children_have_been_deleted/creates_and_pulls_subfile1_and_subfile2.yml
spec/views/folders/show_spec.rb
spec/views/revisions/folders/show_spec.rb

**Fixes:**
- In folders view, generate correct links in the breadcrumbs/anecestry path by
relying on #hashed_file_id ([#246](https://github.com/OpenlyOne/openly/issues/246))
- When force-syncing a folder, pull any new children as well as any children
that have no current or committed version and can thus not be manually
force-synced ([#247](https://github.com/OpenlyOne/openly/issues/247))

Hotfix v0.30.2: Ancestry links & folder force-syncing

---

app/controllers/concerns/can_set_project_context.rb
app/controllers/project_setups_controller.rb
app/views/layouts/file_changes.slim
app/views/layouts/file_infos.slim
app/views/layouts/folders.slim
app/views/layouts/project_overviews.slim
app/views/layouts/project_setups.slim
app/views/layouts/revisions.slim
app/views/layouts/revisions/file_changes.slim
app/views/layouts/revisions/folders.slim
app/views/projects/_form.slim
app/views/projects/_head.slim
spec/controllers/project_setups_controller_spec.rb
spec/views/projects/_head_spec.rb

When requesting to see a project's setup status, only collaborators are
granted access. Visitors are denied.
Previously, visitors were granted access as well. We change this because
there is no reason for visitors to need access to the setup status.
This resolves [#255](https://github.com/OpenlyOne/openly/issues/255).

Limit project setup to owner & collaborators

---

app/controllers/admin/profiles/users_controller.rb
app/controllers/application_controller.rb
app/controllers/profiles_controller.rb
app/controllers/project_setups_controller.rb
app/controllers/projects_controller.rb
app/controllers/revisions_controller.rb
app/dashboards/account_dashboard.rb
app/dashboards/profiles/user_dashboard.rb
app/dashboards/project_dashboard.rb
app/models/profiles/user.rb
app/views/fields/belongs_to/_index.html.erb
app/views/fields/belongs_to/_show.html.erb
app/views/fields/has_one/_index.html.erb
app/views/fields/has_one/_show.html.erb
app/views/profiles/edit.slim
app/views/project_overviews/show.slim
app/views/projects/_form.slim
app/views/projects/_project.slim
app/views/projects/edit.slim
app/views/projects/new.slim
config/initializers/bullet.rb
config/routes.rb
spec/features/admin_panel_spec.rb
spec/models/profiles/base_spec.rb
spec/models/shared_examples/being_a_profile.rb

Admins can add or remove users as collaborators on projects. This is done
by going to the Projects tab in the admin panel and clicking Edit on one of
the projects.
This resolves [#250](https://github.com/OpenlyOne/openly/issues/250).

Manage project collaborators via admin panel

---

app/dashboards/project_dashboard.rb
spec/dashboards/account_dashboard_spec.rb
spec/dashboards/profiles/user_dashboard_spec.rb
spec/dashboards/project_dashboard_spec.rb

When searching the project dashboard, Rails has been throwing an internal
error. This is due to the fact that Administrate is attempting to search
the attribute `tag_list` in the database, but `tag_list` is an entirely
virtual attribute (built from the tags array). To avoid the error,
`tag_list` is explicitly removed from the fields to search.

Admin Dashboard: Fix searching for projects

---

app/assets/stylesheets/controllers/profiles.scss
app/assets/stylesheets/shared/buttons.scss
app/assets/stylesheets/shared/colors.scss.erb
app/controllers/profiles_controller.rb
app/models/project.rb
app/models/vcs/branch.rb
app/models/vcs/commit.rb
app/models/vcs/file_in_branch.rb
app/views/folders/show.slim
app/views/projects/_project.slim
config/initializers/bullet.rb
db/migrate/20190210025157_add_uncaptured_changes_count_to_vcs_branches.rb
db/schema.rb
spec/factories/projects.rb
spec/factories/vcs/vcs_file_in_branches.rb
spec/features/file_content_change_spec.rb
spec/features/file_restore_spec.rb
spec/features/revision_restore_spec.rb
spec/features/revision_spec.rb
spec/integrations/project_spec.rb
spec/integrations/vcs/branch_spec.rb
spec/integrations/vcs/file_in_branch_spec.rb
spec/models/project_spec.rb
spec/models/vcs/commit_spec.rb
spec/models/vcs/file_in_branch_spec.rb
spec/views/folders/show_spec.rb
spec/views/profiles/show_spec.rb

Display an indicator for uncaptured file changes on project preview cards as
well as the project's capture changes button. The purpose is to help people be
more aware of projects that have uncaptured work.
Resolves [#305](https://github.com/OpenlyOne/openly/issues/305).

Add uncaptured changes indicator to projects

---

app/assets/stylesheets/controllers/profiles.scss
app/controllers/profiles_controller.rb
app/models/project.rb
app/models/vcs/commit.rb
app/views/projects/_project.slim
db/migrate/20190210093056_add_captured_at_to_projects.rb
db/schema.rb
spec/factories/projects.rb
spec/integrations/project_spec.rb
spec/models/vcs/commit_spec.rb
spec/views/profiles/show_spec.rb

Add a column to the projects table to add the time of the project's last commit.
This time is displayed on the project preview cards and is used to sort projects
in the order of most to least recent commit.
It should help users more quickly
find the projects they are actively working on and it should help those looking
at other users' repositories quickly decide how up-to-date a project is.
Resolves [#79](https://github.com/OpenlyOne/openly/issues/79).

Sort Projects by Recency

---

app/controllers/profiles_controller.rb
app/models/project.rb
spec/features/user_spec.rb
spec/integrations/project_spec.rb

On the profile page, show only projects that the user can view (such as
public projects or private projects where the user is a collaborator).
Private projects that the user cannot view are no longer shown. That is
good because they were meant to be private in the first place.
Resolves [#302](https://github.com/OpenlyOne/openly/issues/302).

Profile page: Show only projects that user can view

---

app/assets/stylesheets/controllers/profiles.scss
app/assets/stylesheets/shared/cards.scss
app/views/projects/_project.slim
spec/views/profiles/show_spec.rb

Add a lock icon to preview cards of private projects to help users
distinguish between private and public projects.
Addresses [#251](https://github.com/OpenlyOne/openly/issues/291)

Project preview cards: Add lock icon for private projects

---

app/assets/stylesheets/shared/chips.scss
app/controllers/projects_controller.rb
app/dashboards/account_dashboard.rb
app/models/ability.rb
app/models/account.rb
app/models/profiles/user.rb
app/models/project.rb
app/views/projects/new.slim
config/locales/en.yml
db/migrate/20190212053330_add_is_premium_to_accounts.rb
db/migrate/20190212095542_remove_column_default_from_projects_is_public.rb
db/schema.rb
spec/controllers/projects_controller_spec.rb
spec/factories/accounts.rb
spec/factories/profiles/base.rb
spec/features/account_spec.rb
spec/features/admin_panel_spec.rb
spec/features/premium_feature_spec.rb
spec/features/project_spec.rb
spec/integrations/profiles/user_spec.rb
spec/models/ability_spec.rb
spec/models/account_spec.rb
spec/models/profiles/user_spec.rb
spec/models/project_spec.rb
spec/support/fixtures/vcr_cassettes/Premium_Users/Premium_user_can_create_private_project.yml
spec/support/fixtures/vcr_cassettes/Project/User_can_create_public_project.yml
spec/views/projects/new_spec.rb

Add support for premium accounts (paid plans). All accounts default to free
accounts. This can be changed via the admin panel.
Free users can only create public projects. Premium users can choose between
creating private and public projects.

Make private projects a premium feature

---

app/views/application/_navbar_signed_in.slim

Use Google's `bell` and `bell-ring` icon as the notifications icon.
`bell` is used when no unread notifications are present.
`bell-ring` is used when unread notifications are present.
Resolves [#318](https://github.com/OpenlyOne/openly/issues/318)

Improve notification icon

---

CHANGELOG.md
app/views/static/_call_to_action.slim
spec/features/static_spec.rb

**Fixes:**
- Relabel CTA on landing page to 'Get Started' because it may invite
more responses than 'Join Waitlist'

Hotfix v0.35.1: Relabel CTA on landing page

---

app/controllers/contributions_controller.rb
app/controllers/projects_controller.rb
app/models/contribution.rb
app/models/vcs/branch.rb
app/models/vcs/commit.rb
app/models/vcs/operations/commit_restore.rb
app/models/vcs/operations/restore_files_from_diffs.rb
app/views/contributions/reviews/_review_and_accept_file_changes_form.slim
db/migrate/20190215234419_add_origin_revision_to_contributions.rb
db/schema.rb
spec/controllers/contributions/acceptances_controller_spec.rb
spec/controllers/contributions_controller_spec.rb
spec/factories/contributions.rb
spec/factories/vcs/vcs_commits.rb
spec/features/contributions/acceptances_spec.rb
spec/features/contributions/review_changes_spec.rb
spec/integrations/contribution_spec.rb
spec/integrations/vcs/branch_spec.rb
spec/integrations/vcs/commit_spec.rb
spec/integrations/vcs/operations/restore_files_from_diffs_spec.rb
spec/models/contribution_spec.rb
spec/models/vcs/branch_spec.rb
spec/models/vcs/commit_spec.rb
spec/support/fixtures/vcr_cassettes/Contribution/_setup/copies_files_from_origin_revision.yml
spec/support/fixtures/vcr_cassettes/Contributions_Acceptances/User_can_accept_suggested_changes.yml
spec/views/contributions/reviews/show_spec.rb

When calculating suggested changes in a contribution, calculate them relative to
the contribution's origin revision — **not the current latest revision in
project** — and do not overwrite any other files.
This makes contributions a lot more useful because many contributions can be
worked on at the same time without overwriting each other's changes. It also
makes contributions a lot less dangerous because the potential of overwriting
uncaptured changes in the master is limited to those files having changes
suggested by the contribution.
Resolves [#325](https://github.com/OpenlyOne/openly/issues/325)
Fixes [#328](https://github.com/OpenlyOne/openly/issues/328)

Contribution: Apply suggested changes relative to origin revision

---

app/views/contributions/_head.slim
spec/views/contributions/_head_spec.rb

Allow users to open the contribution's root folder in Google Drive via
the contribution header navigation.
Resolves [#273](https://github.com/OpenlyOne/openly/issues/273)

Contributions: Add link to open in Google Drive

---

app/controllers/accounts_controller.rb
app/models/account.rb
config/routes.rb
spec/controllers/accounts_controller_spec.rb
spec/models/account_spec.rb
spec/routing/account_routing_spec.rb

Admins can update email addresses of accounts via the admin panel. Users
**cannot** update their own email address.
Resolves [#266](https://github.com/OpenlyOne/openly/issues/266)

Account: Allow email update

---

app/views/static/github_for_documents/index.slim
app/views/static/open_collaboration/index.slim

We are (soon) dissolving the legal entity called Openly One Inc. We will
continue to keep the website up as an open source passion project. The
footer now reflects that.

Change footer: Openly One Inc is now Team Openly
