OpenlyOne/openly

app/views/layouts/application.slim

Let the browser know that the site is optimized for mobile devices.

Add viewport meta tag to <head>

---

spec/models/user_spec.rb

Change subject from :account to :user.

Fix: Subject should be :user in models/user_spec

---

app/assets/stylesheets/shared/all.scss
app/assets/stylesheets/shared/typography.scss

Set h1, h2, h3, ... font-size responsively. Larger screens have larger heading sizes.

Responsively set font-size for h-tags

---

app/controllers/application_controller.rb
app/controllers/profiles_controller.rb
app/helpers/layout_helper.rb
app/models/profile.rb
app/models/user.rb
config/routes.rb
spec/controllers/profiles_controller_spec.rb
spec/controllers/shared_examples/raise_404_if_non_existent.rb
spec/helpers/layout_helper_spec.rb
spec/models/profile_spec.rb
spec/models/user_spec.rb

- Use route key 'profiles' for User model to enable url_for helpers
- Refactor spec for ProfilesController
- Refactor ProfilesController

Refactor Profiles

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/projects_controller.rb
app/models/concerns/version_control.rb
app/models/project.rb
app/models/version_control/file.rb
app/models/version_control/file_collection.rb
app/models/version_control/repository.rb
app/views/projects/show.slim
config/settings.yml
config/settings/test.yml
spec/controllers/projects_controller_spec.rb
spec/factories/version_control/file.rb
spec/factories/version_control/file_collection.rb
spec/factories/version_control/repository.rb
spec/features/project_spec.rb
spec/models/project_spec.rb
spec/models/shared_examples/having_version_control.rb
spec/models/version_control/file_collection_spec.rb
spec/models/version_control/file_spec.rb
spec/models/version_control/repository_spec.rb
spec/rails_helper.rb
spec/support/tmp_file_cleaner.rb
spec/views/projects/show_spec.rb

Projects (or rather, their files) are under version control. Every file change (create, edit, rename, destroy) creates a commit to the repository. Version control is powered by Git.

Set up version control

---

app/models/ability.rb
spec/models/user_spec.rb

1. Fix: Spelling in user spec
2. Fix: Spelling in ability definitions

Various Fixes

---

app/controllers/application_controller.rb
app/controllers/files_controller.rb
app/controllers/projects_controller.rb
config/locales/en.yml
spec/controllers/files_controller_spec.rb
spec/controllers/projects_controller_spec.rb
spec/controllers/shared_examples/a_redirect_with_success.rb

- Refactor successful redirect into method #redirect_with_success_to
- Refactor spec for successful redirect into shared example

Refactor Controller Redirects

---

spec/factories/version_control/file.rb
spec/factories/version_control/repository.rb
spec/models/version_control/file_spec.rb

- VersionControl::File factory: Create revision_author on create
- VersionControl::Repository factory: Generate unique repository name (using sequence)

Fix factories

---

app/assets/stylesheets/shared/buttons.scss
app/controllers/files_controller.rb
app/helpers/file_helper.rb
app/models/concerns/version_control.rb
app/models/version_control/contribution.rb
app/models/version_control/file.rb
app/models/version_control/file_collection.rb
app/views/files/_file.slim
app/views/files/_file_action.slim
app/views/files/_form.slim
app/views/files/_meta.slim
app/views/files/index.slim
app/views/files/show.slim
app/views/projects/_head.slim
db/migrate/20171017180646_add_file_count_to_project.rb
db/schema.rb
spec/controllers/files_controller_spec.rb
spec/factories/version_control/contribution.rb
spec/features/file_spec.rb
spec/helpers/file_helper_spec.rb
spec/models/shared_examples/having_version_control.rb
spec/models/version_control/contribution_spec.rb
spec/models/version_control/file_collection_spec.rb
spec/models/version_control/file_spec.rb
spec/views/files/index_spec.rb
spec/views/files/show_spec.rb

- Follow design & style of discussions
- Add meta information to files (last contribution summary, author, and date)
- Add counter cache for files count on projects

Makeover for project files

---

app/assets/stylesheets/shared/colors.scss.erb
app/assets/stylesheets/shared/forms.scss
app/assets/stylesheets/shared/tabs.scss
app/models/color.rb
app/views/revisions/new.slim

- Do not truncate tab text
- Fix: Textarea and label alignment
- Change color scheme to blue darken-3

Three tiny design changes

---

app/controllers/profiles_controller.rb
app/controllers/projects_controller.rb
app/models/profiles/base.rb
app/models/profiles/user.rb
app/models/project.rb
app/views/profiles/show.slim
spec/factories/projects.rb
spec/features/collaborator_spec.rb
spec/integrations/project_spec.rb
spec/models/profiles/user_spec.rb
spec/models/shared_examples/being_a_profile.rb

Display both projects owned by the profile as well as projects in which the profile is a collaborator on profile pages.

List collaborations on profile page

---

app/models/concerns/syncable.rb
app/models/file_resource.rb
app/models/file_resources/google_drive.rb
app/models/providers/google_drive/api_connection.rb
app/models/providers/google_drive/file_sync.rb
spec/integrations/file_resources/google_drive_spec.rb
spec/integrations/shared_examples/including_syncable_integration.rb
spec/models/providers/google_drive/api_connection_spec.rb
spec/models/providers/google_drive/file_sync_spec.rb
spec/models/shared_examples/being_a_file_resource.rb
spec/models/shared_examples/being_syncable.rb
spec/support/fixtures/vcr_cassettes/FileResources_GoogleDrive/it_should_behave_like_including_syncable_integration/_pull_children/has_children_subfile1_and_subfile2.yml
spec/support/fixtures/vcr_cassettes/FileResources_GoogleDrive/it_should_behave_like_including_syncable_integration/_pull_children/when_sub1_is_deleted_and_sub3_is_added/has_children_subfile2_and_subfile3.yml
spec/support/fixtures/vcr_cassettes/FileResources_GoogleDrive/it_should_behave_like_including_syncable_integration/_pull_children/when_subfile1_is_deleted_and_subfile3_is_added/updates_children_to_subfile2_and_subfile3.yml

Syncable file resources can fetch a fresh list of children from their
provider and persist those children to the database by finding existing
records or creating new ones.

Syncable: Add #pull_children

---

CHANGELOG.md
README.md
lib/tasks/performance/commit_all_files_staged_in_project/prepare.rake
lib/tasks/performance/generate_diffs_for_origin_revision/prepare.rake
lib/tasks/performance/generate_diffs_for_revision_with_parent/prepare.rake

**Fixes:**
- Remove `require 'factory_girl'` statement from rake tasks

Hotfix v0.13.1

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/ahoy/event.rb
app/models/ahoy/visit.rb
app/models/profiles/user.rb
config/initializers/ahoy.rb
db/migrate/20180307134226_create_ahoy_visits_and_events.rb
db/schema.rb
spec/models/profiles/user_spec.rb

Add Ahoy ('ahoy_matey') for tracking site visits and site actions by users.

Tracking with Ahoy

---

spec/features/file_update_spec.rb
spec/support/fixtures/vcr_cassettes/File_Update/In_Google_Drive_user_creates_file_within_project_folder.yml
spec/support/fixtures/vcr_cassettes/File_Update/In_Google_Drive_user_deletes_file.yml
spec/support/fixtures/vcr_cassettes/File_Update/In_Google_Drive_user_deletes_the_project_folder.yml
spec/support/fixtures/vcr_cassettes/File_Update/In_Google_Drive_user_moves_file_out_of_project_folder.yml
spec/support/fixtures/vcr_cassettes/File_Update/In_Google_Drive_user_moves_file_to_the_root_of_their_drive.yml
spec/support/fixtures/vcr_cassettes/File_Update/In_Google_Drive_user_moves_file_within_project_folder.yml
spec/support/fixtures/vcr_cassettes/File_Update/In_Google_Drive_user_renames_file.yml
spec/support/fixtures/vcr_cassettes/File_Update/In_Google_Drive_user_stops_sharing_file.yml
spec/support/fixtures/vcr_cassettes/File_Update/In_Google_Drive_user_trashes_file.yml
spec/support/fixtures/vcr_cassettes/File_Update/In_Google_Drive_user_updates_file_content.yml

Do not reference project until
`given_project_is_imported_and_changes_committed` to avoid importing
files & folders ahead of time.

Fix file update spec: Delay folder import

---

CHANGELOG.md
README.md
app/models/project/setup.rb
spec/integrations/project/setup_spec.rb
spec/models/project/setup_spec.rb
spec/support/fixtures/vcr_cassettes/Folder_Import/Files_are_imported.yml
spec/support/fixtures/vcr_cassettes/Project_Setup/validations/when_link_ends_with_usp_sharing/is_valid.yml
spec/support/fixtures/vcr_cassettes/Project_Setup/validations/when_link_is_a_google_drive_doc/adds_an_error.yml
spec/support/fixtures/vcr_cassettes/Project_Setup/validations/when_link_is_drive_google_com/open_id_/is_valid.yml
spec/support/fixtures/vcr_cassettes/Project_Setup/validations/when_link_looks_like_google_drive_folder_but_has_ID_of_doc/adds_an_error.yml
spec/support/fixtures/vcr_cassettes/Project_Setup/validations/when_link_to_google_drive_folder_is_inaccessible/adds_an_error.yml
spec/support/fixtures/vcr_cassettes/Project_Setup/validations/when_link_to_google_drive_folder_is_invalid/adds_an_error.yml

**Fixes:**
- In project setup, support different formats for Google Drive folder links

Hotfix v0.15.2

---

CHANGELOG.md
README.md
app/models/ability.rb
spec/features/collaborator_spec.rb
spec/models/ability_spec.rb

**Fixes:**
- Collaborators can initiate project setup process

Hotfix v0.15.3

---

app/assets/stylesheets/shared/document.scss
app/assets/stylesheets/shared/image.scss

Background color was not showing up in a few browsers because it was set on the body element. Fix this by setting background color on \<main\>.

Fix: Set background color to gray lighten-4

---

CHANGELOG.md
README.md
app/assets/stylesheets/controllers/folders.scss
config/deploy.rb

**Fixes:**
- Show file infos icon when hovering files

Hotfix v0.16.1

---

Gemfile
Gemfile.lock
Guardfile
bin/rspec

Speed up Rspec by using gem 'spring-commands-rspec'.

Speed up Rspec

---

app/assets/stylesheets/mixins/seam.scss
app/assets/stylesheets/shared/colors.scss.erb
app/assets/stylesheets/shared/navbar.scss
app/assets/stylesheets/variables.scss
app/controllers/profiles_controller.rb
app/helpers/layout_helper.rb
app/models/color.rb
app/models/profiles/base.rb
app/views/application/_navbar.slim
app/views/layouts/application.slim
db/migrate/20180413212022_add_color_scheme_to_profiles.rb
db/schema.rb
spec/factories/profiles/base.rb
spec/helpers/layout_helper_spec.rb
spec/models/color_spec.rb
spec/models/profiles/user_spec.rb
spec/models/shared_examples/being_a_profile.rb

Profiles can choose from 256 color schemes with which to paint their profile page.

Add color scheme to profiles

---

CHANGELOG.md
app/models/concerns/vcs/resourceable.rb
app/models/vcs/file_record.rb
app/models/vcs/file_thumbnail.rb
app/models/vcs/repository.rb
config/initializers/paperclip.rb
db/migrate/20181106234927_add_file_record_id_to_vcs_file_thumbnails.rb
db/migrate/20181107063808_change_column_null_of_file_thumbnails.rb
db/schema.rb
lib/tasks/data_migration/file_thumbnails.rake
spec/factories/vcs/vcs_file_thumbnails.rb
spec/factories/vcs/vcs_staged_files.rb
spec/integrations/file_resource/thumbnail_spec.rb
spec/integrations/project_spec.rb
spec/integrations/vcs/file_thumbnail_spec.rb
spec/lib/tasks/data_migration/file_thumbnails_spec.rb
spec/models/shared_examples/vcs/being_resourceable.rb
spec/models/vcs/file_record_spec.rb
spec/models/vcs/file_thumbnail_spec.rb
spec/support/fixtures/vcr_cassettes/File_Update/In_Google_Drive_user_updates_file_content.yml
spec/support/fixtures/vcr_cassettes/Revision_Restore/restores_a_prior_revision.yml

**Fixes:**
- Deleting projects is now possible again (it caused server errors due to the
way that file thumbnails were implemented)

Hotfix v0.26.3: Fix project deletion

---

.travis.yml
app/assets/stylesheets/controllers/revisions.scss
app/controllers/force_syncs_controller.rb
app/models/concerns/vcs/diffing.rb
app/models/concerns/vcs/downloadable.rb
app/models/concerns/vcs/syncable.rb
app/models/file_diff/change.rb
app/models/vcs/commit.rb
app/models/vcs/file_snapshot.rb
app/models/vcs/operations/content_change_fragment.rb
app/models/vcs/operations/content_differ.rb
app/views/revisions/_content_change_fragment.slim
app/views/revisions/_file_change.slim
config/initializers/bullet.rb
spec/features/file_content_change_spec.rb
spec/features/force_sync_spec.rb
spec/integrations/vcs/operations/content_differ_spec.rb
spec/models/shared_examples/being_a_file_diff_change.rb
spec/models/shared_examples/vcs/being_diffing.rb
spec/models/shared_examples/vcs/being_downloadable.rb
spec/models/shared_examples/vcs/being_syncable.rb
spec/models/vcs/file_snapshot_spec.rb
spec/models/vcs/operations/content_change_fragment_spec.rb
spec/models/vcs/operations/content_differ_spec.rb
spec/support/fixtures/vcr_cassettes/Force_Sync/User_can_force_sync_file.yml
spec/views/file_infos/index_spec.rb
spec/views/revisions/index_spec.rb
spec/views/revisions/new_spec.rb

On revisions page, capture changes page, and file info page, show content
changes for modified text files (Google doc, odt, docx, doc, and pdf).

Show file content changes

---

.travis.yml
app/models/project.rb
app/models/providers/google_drive/api_connection.rb
app/models/vcs/archive.rb
config/application.yml.example
spec/features/collaborator_spec.rb
spec/integrations/providers/google_drive/api_connection_spec.rb
spec/models/project_spec.rb
spec/models/vcs/archive_spec.rb
spec/support/fixtures/google_drive/credentials.yml
spec/support/fixtures/vcr_cassettes/Collaborators_As_a_collaborator/when_project_has_an_archive/I_have_view_access_to_the_archive.yml
spec/support/fixtures/vcr_cassettes/Collaborators_As_a_collaborator/when_project_has_an_archive/when_I_am_removed_as_a_collaborator/I_no_longer_have_read_access_to_the_archive.yml
spec/support/fixtures/vcr_cassettes/Providers_GoogleDrive_ApiConnection/_share_file/grants_read_permission_to_the_recipient.yml
spec/support/fixtures/vcr_cassettes/Providers_GoogleDrive_ApiConnection/_share_file/when_file_has_already_been_shared_with_the_recipient/1_1_2_1.yml
spec/support/fixtures/vcr_cassettes/Providers_GoogleDrive_ApiConnection/_unshare_file/grants_read_permission_to_the_recipient.yml
spec/support/fixtures/vcr_cassettes/Providers_GoogleDrive_ApiConnection/_unshare_file/removes_read_permission_from_the_recipient.yml
spec/support/fixtures/vcr_cassettes/Providers_GoogleDrive_ApiConnection/_unshare_file/when_file_has_already_been_unshared_with_the_recipient/1_2_2_1.yml
spec/support/vcr_configuration.rb

- Grant access to the project archive to collaborators who are added
- Remove access to the project archive from collaborators who are removed

Grant archive access to project collaborators

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/views/admin/application/_navigation.slim
config/blazer.yml
config/routes.rb
db/migrate/20181120031717_install_blazer.rb
db/schema.rb
spec/features/admin_panel_spec.rb

Install blazer for an analytics dashboard, so that we get a better idea
of how users are using our platform and can identify ways to make it
better and more valuable.

Analytics Dashboard

---

app/assets/stylesheets/shared/cards.scss
app/views/devise/registrations/_card.slim
app/views/projects/_project.slim
spec/views/profiles/show_spec.rb

Use the new, minimalist style for the project preview cards.
Resolves [#291](https://github.com/OpenlyOne/openly/issues/291).

Update project preview cards

---

CHANGELOG.md
app/views/contributions/_head.slim
app/views/contributions/replies/index.slim
app/views/layouts/contributions/replies.slim
spec/controllers/contributions/replies_controller_spec.rb

**Fixes:**
- Add page layout for contribution discussion page to have the project
and contribution navigation rendered

Hotfix v0.36.1: Add layout for contribution discussion page
